"""empty message

Revision ID: 4c39981e3069
Revises: e8e6a28e585b
Create Date: 2024-06-24 22:13:05.052017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel 

# revision identifiers, used by Alembic.
revision: str = '4c39981e3069'
down_revision: Union[str, None] = 'e8e6a28e585b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regions', sa.Column('transit_service_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regions', 'transit_service_url')
    # ### end Alembic commands ###
